# Generated by Django 3.2.2 on 2021-05-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='账号')),
            ],
            options={
                'db_table': 'user1',
            },
        ),
    ]
