# Generated by Django 3.2.2 on 2021-05-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('collect_id', models.AutoField(primary_key=True, serialize=False, verbose_name='收藏id')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('save_id', models.IntegerField(verbose_name='存的商品id')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('good_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品id')),
                ('good_name', models.CharField(max_length=20, verbose_name='商品名')),
                ('good_introduce', models.TextField(verbose_name='简介')),
                ('good_num', models.IntegerField(verbose_name='商品剩余数量')),
                ('good_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('good_picture', models.ImageField(default='', upload_to='static/img/good', verbose_name='商品图片')),
            ],
        ),
        migrations.CreateModel(
            name='User2',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='账号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='User1',
        ),
    ]
